services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Services\TaskFactory:
    public: true

  App\Services\TaskTypeLoader:
    public: true

  App\Services\UrlFactory:
    public: true
